# Generated by Django 5.0.3 on 2024-03-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_dish_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
