# Generated by Django 5.0.3 on 2024-03-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_cook_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "dishes", "verbose_name_plural": "dishes"},
        ),
    ]
