# Generated by Django 5.0.3 on 2024-03-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_alter_dish_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={},
        ),
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                related_name="cooks", to=settings.AUTH_USER_MODEL, verbose_name="dishes"
            ),
        ),
    ]
