# Generated by Django 5.0.3 on 2024-03-19 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0007_alter_dish_options_alter_dish_cooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                related_name="cooks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
